# Site settings
title: Aproid
email: you171717@naver.com
author: Aproid
description: >-
  알고보면 유용한 사람.
baseurl: ""
url: https://aproid.github.io

# Frontend variables
asset_url: /assets
# cover: /assets/images/blog-cover.png
# favicon: /assets/images/favicon.jpg
# logo:
# logo_dark:

# Environment settings
language: 'ko-kr'
timezone: Asia/Seoul
permalink: /:year/:month/:day/:title/
excerpt_separator: <!--more-->

# Collection settings
collections:
  category:
    output: true
    permalink: /category/:name/
defaults:
  - scope:
      path: ""
      type: "category"
    values:
      layout: category

# Build settings
port: 8080
markdown: kramdown
highlighter: rouge
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
keep_files:
  - assets
  - files
  - .git
  - .svn
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  
# Plugin settings
feed:
  path: feed.xml

# Social settings
github: [metadata]
github_username:  aproid
twitter_username: ArtisanAproid