# Site settings
title: Aproid
email: you171717@naver.com
author: Aproid
description: >-
  알고보면 유용한 사람.
baseurl: ""
url: https://aproid.github.io

# Frontend variables
asset_url: /assets
# cover: /assets/images/blog-cover.png
# favicon: /assets/images/favicon.jpg
# logo:
# logo_dark:

# Environment settings
language: 'ko-kr'
timezone: Asia/Seoul
permalink: /:year/:month/:day/:title/
excerpt_separator: <!--more-->

# Collection settings
collections:
  category:
    output: true
    permalink: /:slug/
defaults:
  - scope:
      path: ''
      type: category
    values:
      layout: category

# Build settings
port: 8080
markdown: kramdown
kramdown: 
  parse_block_html: true
  input:          GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
highlighter: rouge
sass:
  style: compressed
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
keep_files:
  - assets
  - files
  - .git
  - .svn
plugins:
#  - jekyll-feed
#  - jekyll-sitemap
#  - jekyll-seo-tag
  
# Plugin settings
paginate: 10
paginate_path: "/:num/"
feed:
  path: feed.xml
  

# Social settings
github: [metadata]
github_username: aproid
twitter_username: ArtisanAproid
disqus_username: aproid